Repository argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi, pull requests merged in 2024-02, with the labels that each got.

#31 feat: Add setHeader functionality for httpRoutes
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  internal/defaults/defaults.go
  internal/utils/common.go
  internal/utils/types.go
  main.go
  pkg/mocks/plugin.go
  pkg/plugin/errors.go
  pkg/plugin/httproute.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/plugin/tcproute.go
  pkg/plugin/types.go
  utils/common.go
Labels: enhancement

#35 docs: update documentation about plugin system issue
  README.md
Labels: documentation

#37 fix: handle the signal removeManagedRoutes before creating config map
  internal/utils/common.go
  pkg/plugin/httproute.go
Labels: bug

#34 feat: support multiple routes per rollout
  examples/traefik/README.md
  go.mod
  go.sum
  main.go
  pkg/mocks/plugin.go
  pkg/plugin/errors.go
  pkg/plugin/httproute.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/plugin/tcproute.go
  pkg/plugin/types.go
Labels: enhancement
